### ISSUE TITLE
Разработать дизайн виселицы

### ISSUE THREAD

**Issue by dmitrytavern** [dmitrytavern/university-hangman#2]
Дизайн виселицы определяет глубокое ТЗ продукта (хоть это и не так) и должен прорабатывать разные сценарии взаимодействия.

Требования:
- Приложение: Figma (желательно) или Qt Designer
- Внешний вид: должен учитывать возможность растяжения (если предусмотрено ТЗ), должен иметь один стиль, один цвет primary и secondary цветов и их оттенков.
- Должен быть экран приветствия, где нам предлагают: Начать игру, Узнать разработчиков.
- Должен быть экран пред-игры, где просят ввести имя первого и второго игрока
- Должен быть экран самой игры, где есть 2 висильнцы, блок с угаданныи буквами для каждого игрока, поле для ввода, кнопка, возможность закрыть игру и выйти в экран приветсивия.
- Должен быть экран About dev, где будет показана инфо об проекте.

**Comment by DenStrateg** [comment]
https://www.figma.com/file/IrVOXPkgr5nTszE7dPDlrw/Hangman?type=design&node-id=0-1&t=pCjcRaTikcMZojv8-0
