### ISSUE TITLE
Разработать иконку виселицы

### ISSUE THREAD

**Issue by dmitrytavern** [dmitrytavern/university-hangman#3]
Необходимо разработать иконку, которая будет использоватся на сайте документации, и ввиде appicon для бинарника.

Требования:
- Формат: svg
- Цвет: желательно использовать один цвет
- Описание: должна быть похожа на виселицу, должна быть согласована с дизайном проекта

**Comment by DenStrateg** [comment]
![Image](https://github.com/dmitrytavern/university-hangman/assets/106665225/32227064-7da3-4e8c-9fde-4e20db70f738)
