### ISSUE TITLE
Подготовить призентацию по первому спринту

### ISSUE THREAD

**Issue by dmitrytavern** [dmitrytavern/university-hangman#4]
Подготовка призентации основывается на разработаном ТЗ, дизайном, архитектурой и должна включать следующее:

- Вступление: рассказ о базовом ТЗ, которое нам предоставил заказчик
- ТЗ: рассказ о нашем разработанном ТЗ, которое должно включать самые основные детали (можно использовать обощения, а так же не упоминать мелкие детали)
- UI: рассказ о нашем разработанном дизайне, его скриншоты, а так же как описание как программа будет использована и как это предусмотрено дизайном.
- 2 спринт: рассказ о том, чем мы будем заниматся на втором спринте.

Требования:
- Общее оформление: должен использоватся стиль дизайна нашего проекта
- Язык: украинский/английских

**Comment by Podionboz** [comment]
[Project.pdf](https://github.com/dmitrytavern/university-hangman/files/11536166/Project.pdf)

**Comment by dmitrytavern** [comment]
[handman.pdf](https://github.com/dmitrytavern/university-hangman/files/11540098/handman.pdf)
